/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'webonise' at '11/2/16 6:11 PM' with Gradle 2.10
 *
 * @author webonise, @date 11/2/16 6:11 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
