/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'webonise' at '11/2/16 6:11 PM' with Gradle 2.10
 *
 * @author webonise, @date 11/2/16 6:11 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
